services:
  - type: web
    name: task-manager-backend
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
